### ISSUE TITLE
algo/binary-search-tree

### ISSUE THREAD

**Issue by lulalachen** [lulalachen/algorithm#9]
Binary Search Tree
- [ ] Basic Constructions
- [ ] BFS (breath-first-search)
- [ ] DFS (depth-first-search)
- [ ] Tree to linked list
- [ ] Tree to lists of layers
